### ISSUE TITLE
no media files in ....

### ISSUE THREAD

**Issue by nyok92** [immstudios/conti#4]
ERROR       There are no media files in '/media.dir'
DEBUG       Critical error. Terminating program.

Hi, i tried different folders and syntax but each times it failed. The media files have to be of a specific type ?
Does absolute path should be working ?
Thanks for any help !

**Comment by martastain** [comment]
There is a whitelist in the example script which only checks for mov and mxf files. But both absolute and relative paths should work.  conti.py is really just an example - you should copy it and tweak it according to your needs.
